### Get all hotels
GET http://localhost:7000/hotel

### Get hotel by ID
GET http://localhost:7000/hotel/4

### Get rooms for hotel
GET http://localhost:7000/hotel/4/rooms

### Create a new hotel
POST http://localhost:7000/hotel
Content-Type: application/json

{
  "name": "Hotel 3",
  "address": "Address 3"
}

### Update a hotel
PUT http://localhost:7000/hotel/1
Content-Type: application/json

{
  "name": "Hotel renamedHotel",
  "address": "Address 1"
}

### Delete a hotel
DELETE http://localhost:7000/hotel/3

### Add room to hotel
POST http://localhost:7000/hotel/5/room
Content-Type: application/json

{
  "id": 2,
  "number": 101,
  "price": 150.0
}

### Remove room from hotel
DELETE http://localhost:7000/hotel/1/room/1
